<a href="https://colab.research.google.com/github/parkrye/Python/blob/main/Others/%EC%A0%84%EB%B3%B5_%EB%82%98%EC%9D%B4_%EC%98%88%EC%B8%A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 세팅

In [ ]:
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn
!pip install sklearn

Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.3.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2018.9)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.21.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (1.21.5)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (3.2.2)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib) (1.3.2)
Requirement already satisfied: numpy>=1.11 in /usr/local/lib/python3.7/dist-packages (from matplotlib) (1.21.5)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib) (0.11.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib) (3.0.7)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib) (1.15.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.7/dist-packages (0.11.2)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.7/dist-packages (from seaborn) (1.21.5)
Requirement already satisfied: matplotlib>=2.2 in /usr/local/lib/python3.7/dist-packages (from seaborn) (3.2.2)
Requirement already satisfied: pandas>=0.23 in /usr/local/lib/python3.7/dist-packages (from seaborn) (1.3.5)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.7/dist-packages (from seaborn) (1.4.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.2->seaborn) (3.0.7)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.2->seaborn) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.2->seaborn) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.2->seaborn) (0.11.0)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23->seaborn) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib>=2.2->seaborn) (1.15.0)
Requirement already satisfied: sklearn in /usr/local/lib/python3.7/dist-packages (0.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (from sklearn) (1.0.2)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->sklearn) (1.4.1)
Requirement already satisfied: numpy>=1.14.6 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->sklearn) (1.21.5)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->sklearn) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->sklearn) (3.1.0)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from tensorflow import keras

In [ ]:
#csv 파일 경로
train_data = pd.read_csv("/content/drive/MyDrive/Colab_Notebooks/Dacon/002/train.csv")
test_data = pd.read_csv("/content/drive/MyDrive/Colab_Notebooks/Dacon/002/test.csv")

# 본문

## 데이터 요약

In [ ]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1253 entries, 0 to 1252
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              1253 non-null   int64
 1   Gender          1253 non-null   object
 2   Lenght          1253 non-null   float64
 3   Diameter        1253 non-null   float64
 4   Height          1253 non-null   float64
 5   Whole Weight    1253 non-null   float64
 6   Shucked Weight  1253 non-null   float64
 7   Viscra Weight   1253 non-null   float64
 8   Shell Weight    1253 non-null   float64
 9   Target          1253 non-null   int64
dtypes: float64(7), int64(2), object(1)
memory usage: 98.0+ KB

In [ ]:
train_data.describe()

,id,Lenght,Diameter,Height,Whole Weight,Shucked Weight,Viscra Weight,Shell Weight,Target
count,1253.000000,1253.000000,1253.000000,1253.000000,1253.000000,1253.000000,1253.000000,1253.000000,1253.000000
mean,627.000000,0.522869,0.406963,0.139545,0.831199,0.358818,0.181006,0.240077,9.912211
std,361.854252,0.120231,0.099771,0.039033,0.500491,0.224612,0.111936,0.142574,3.214676
min,1.000000,0.110000,0.090000,0.030000,0.008000,0.002500,0.002000,0.003000,3.000000
25%,314.000000,0.445000,0.345000,0.115000,0.440500,0.182500,0.092500,0.130000,8.000000
50%,627.000000,0.535000,0.420000,0.140000,0.777500,0.326000,0.168000,0.230000,10.000000
75%,940.000000,0.615000,0.480000,0.165000,1.160000,0.505500,0.256500,0.330000,11.000000
max,1253.000000,0.780000,0.630000,0.250000,2.779500,1.488000,0.760000,1.005000,29.000000

In [ ]:
train_data.head()

,id,Gender,Lenght,Diameter,Height,Whole Weight,Shucked Weight,Viscra Weight,Shell Weight,Target
0,1,M,0.605,0.470,0.115,1.1140,0.3925,0.2910,0.3100,15
1,2,I,0.430,0.315,0.095,0.3780,0.1750,0.0800,0.1045,8
2,3,I,0.580,0.490,0.195,1.3165,0.5305,0.2540,0.4100,18
3,4,M,0.535,0.405,0.175,1.2705,0.5480,0.3265,0.3370,13
4,5,I,0.310,0.235,0.090,0.1270,0.0480,0.0310,0.0400,6

## 데이터 전처리

In [ ]:
train_data.set_index('id', inplace= True)
test_data.set_index('id', inplace= True)

In [ ]:
train_data.loc[train_data['Gender'] == 'unknown', 'Gender'] = int(0)
train_data.loc[train_data['Gender'] == 'M', 'Gender'] = int(1)
train_data.loc[train_data['Gender'] == 'I', 'Gender'] = int(2)
train_data.loc[train_data['Gender'] == 'F', 'Gender'] = int(3)

test_data.loc[test_data['Gender'] == 'unknown', 'Gender'] = int(0)
test_data.loc[test_data['Gender'] == 'M', 'Gender'] = int(1)
test_data.loc[test_data['Gender'] == 'I', 'Gender'] = int(2)
test_data.loc[test_data['Gender'] == 'F', 'Gender'] = int(3)

In [ ]:
train_data.head()

,Gender,Lenght,Diameter,Height,Whole Weight,Shucked Weight,Viscra Weight,Shell Weight,Target
id,,,,,,,,,
1,1,0.605,0.470,0.115,1.1140,0.3925,0.2910,0.3100,15
2,2,0.430,0.315,0.095,0.3780,0.1750,0.0800,0.1045,8
3,2,0.580,0.490,0.195,1.3165,0.5305,0.2540,0.4100,18
4,1,0.535,0.405,0.175,1.2705,0.5480,0.3265,0.3370,13
5,2,0.310,0.235,0.090,0.1270,0.0480,0.0310,0.0400,6

## 예측

### RandomForest

In [ ]:
train_X = train_data.drop(['Target'], axis=1)
train_y = train_data.Target

model = RandomForestRegressor()
model.fit(train_X, train_y)

prediction = model.predict(test_data)

submission = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/Dacon/002/sample_submission.csv')
submission['Target'] = prediction
submission = submission.astype(int)

submission.to_csv('submit1.csv', index = False)

### 선형회귀

In [ ]:
X = train_data.drop(['Target'], axis=1)
y = train_data.iloc[:, -1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
regr = LinearRegression()
regr.fit(X_train, y_train)

predcition = regr.predict(test_data)

submission = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/Dacon/002/sample_submission.csv')
submission['Target'] = prediction
submission = submission.astype(int)
submission.head()

submission.to_csv('submit2.csv', index = False)

선형 회귀 모델 점수 : 0.455

### Simple NN

In [ ]:
train_data = pd.read_csv("/content/drive/MyDrive/Colab_Notebooks/Dacon/002/train.csv")
test_data = pd.read_csv("/content/drive/MyDrive/Colab_Notebooks/Dacon/002/test.csv")

y_train = train_data['Target']
train_data.drop(['id', 'Target'], axis = 1, inplace = True)
train_data = pd.get_dummies(train_data)
test_data.drop(['id'], axis = 1, inplace = True)
test_data = pd.get_dummies(test_data)

X_train = train_data.values
y_train = y_train.values
X_test = test_data.values

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
y_train_scaled = (y_train - y_train.min()) ** 2 / (y_train.max() - y_train.min())
median = np.median(y_train_scaled)
y_train_scaled = y_train_scaled - median

weight_decay = 1e-5
learning_rate = 1e-3

model = keras.Sequential([
                          keras.layers.Dense(128, activation = 'tanh', input_shape = (X_train.shape[1],), 
                                             kernel_regularizer = keras.regularizers.l2(weight_decay)),
                          keras.layers.Dense(64, activation = 'tanh', kernel_regularizer = keras.regularizers.l2(weight_decay)),
                          keras.layers.Dense(32, activation = 'tanh', kernel_regularizer = keras.regularizers.l2(weight_decay)),
                          keras.layers.Dropout(0),
                          keras.layers.Dense(1)
])

model.compile(optimizer = keras.optimizers.Adam(learning_rate = learning_rate), loss = 'mae', metrics = ['mae'])
early_stopping = keras.callbacks.EarlyStopping(monitor = 'val_loss', patience = 30, restore_best_weights = True)
lr_scheduler = keras.callbacks.ReduceLROnPlateau(monitor = 'val_loss', factor = 0.5, patience = 10, verbose = 0, mode = 'auto', min_delta = 0.0001, cooldown = 0, min_lr = 0)

y_hat = model.predict(X_test_scaled)
y_hat_unscaled = (y_hat + median) / 2 * (y_train.max() - y_train.min()) + y_train.min()
y_hat_unscaled = y_hat_unscaled.astype(int)
y_hat_unscaled = np.clip(y_hat_unscaled, 1, 100)

submission = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/Dacon/002/sample_submission.csv')
submission['Target'] = y_hat_unscaled
submission.to_csv('submit3.csv', index = False)